# Generated by Django 5.0 on 2024-01-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Категория'),
        ),
    ]
